//! The signal runner — `R-E2`/`R-E5`.
//!
//! mogeung never runs agents (ADR-0003) — but running *checks* is a different
//! act: a test suite has no conversation loop to re-acquire. Even so the
//! fence here is explicit: a signal command runs only when a human clicks,
//! never on a timer or a file event, and the command is one the human
//! configured per repo themselves.

use chrono::Utc;
use mogeung_core::change::FileChange;
use mogeung_core::verify::{FileCoverage, SignalRun};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

/// A signal command that will not finish is a hung terminal, not a signal.
const TIMEOUT_SECS: u64 = 600;
/// How much combined output tail to keep.
const TAIL_CHARS: usize = 4000;

/// Where coverage tools conventionally leave lcov data, relative to the repo.
/// Checked newest-first after a run; nothing is ever generated by mogeung.
const LCOV_CANDIDATES: &[&str] = &[
    "lcov.info",
    "coverage/lcov.info",
    "target/lcov.info",
    "coverage/lcov/lcov.info",
];

/// Run the configured command in `repo_root`, capture how it went, and — when
/// an lcov file appeared and a session diff is at hand — the coverage of the
/// changed lines only.
pub async fn run(repo_root: &str, command: &str, changed: &[FileChange]) -> SignalRun {
    let started_at = Utc::now();
    let start = std::time::Instant::now();

    let child = tokio::process::Command::new("sh")
        .arg("-c")
        .arg(command)
        .current_dir(repo_root)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .kill_on_drop(true)
        .spawn();

    let mut run = SignalRun {
        command: command.to_string(),
        started_at,
        secs: 0,
        exit: None,
        tail: String::new(),
        coverage: Vec::new(),
    };

    let child = match child {
        Ok(c) => c,
        Err(e) => {
            run.tail = format!("could not start: {e}");
            return run;
        }
    };

    let output = tokio::time::timeout(
        std::time::Duration::from_secs(TIMEOUT_SECS),
        child.wait_with_output(),
    )
    .await;
    run.secs = start.elapsed().as_secs() as i64;

    match output {
        Err(_) => {
            run.tail = format!("timed out after {TIMEOUT_SECS}s and was killed");
        }
        Ok(Err(e)) => {
            run.tail = format!("failed while running: {e}");
        }
        Ok(Ok(out)) => {
            run.exit = out.status.code();
            let mut text = String::from_utf8_lossy(&out.stdout).into_owned();
            text.push_str(&String::from_utf8_lossy(&out.stderr));
            run.tail = tail_of(&text, TAIL_CHARS);

            if !changed.is_empty() {
                if let Some(lcov) = fresh_lcov(Path::new(repo_root), started_at) {
                    run.coverage =
                        coverage_delta(&changed_new_lines(changed), &parse_lcov(&lcov));
                }
            }
        }
    }
    run
}

fn tail_of(s: &str, n: usize) -> String {
    let count = s.chars().count();
    if count <= n {
        return s.to_string();
    }
    s.chars().skip(count - n).collect()
}

/// An lcov file the run just wrote, if any. Older files are stale coverage of
/// other code and reporting them would be a quiet lie.
fn fresh_lcov(repo_root: &Path, since: chrono::DateTime<Utc>) -> Option<String> {
    for rel in LCOV_CANDIDATES {
        let p = repo_root.join(rel);
        let Ok(meta) = std::fs::metadata(&p) else { continue };
        let Ok(modified) = meta.modified() else { continue };
        if chrono::DateTime::<Utc>::from(modified) >= since {
            return std::fs::read_to_string(&p).ok();
        }
    }
    None
}

/// New-side line numbers each hunk of a diff touched, per file. The hunk
/// header (`@@ -a,b +c,d @@`) gives the start; `+` and ` ` lines advance it,
/// and only `+` lines count as changed.
pub fn changed_new_lines(files: &[FileChange]) -> BTreeMap<String, BTreeSet<u32>> {
    let mut out: BTreeMap<String, BTreeSet<u32>> = BTreeMap::new();
    for f in files {
        let set = out.entry(f.path.clone()).or_default();
        for h in &f.hunks {
            let Some(mut line) = new_start(&h.header) else { continue };
            for l in &h.lines {
                match l.as_bytes().first() {
                    Some(b'+') => {
                        set.insert(line);
                        line += 1;
                    }
                    Some(b'-') => {}
                    _ => line += 1,
                }
            }
        }
    }
    out.retain(|_, v| !v.is_empty());
    out
}

fn new_start(header: &str) -> Option<u32> {
    let plus = header.split('+').nth(1)?;
    plus.split([',', ' ', '@'])
        .next()?
        .parse()
        .ok()
}

/// `SF:`/`DA:` records per file. Everything else in lcov is ignored — line
/// hit counts are the only fact `R-E5` needs.
pub fn parse_lcov(text: &str) -> BTreeMap<String, BTreeMap<u32, u64>> {
    let mut out: BTreeMap<String, BTreeMap<u32, u64>> = BTreeMap::new();
    let mut current: Option<String> = None;
    for line in text.lines() {
        if let Some(path) = line.strip_prefix("SF:") {
            current = Some(path.trim().to_string());
        } else if let Some(rec) = line.strip_prefix("DA:") {
            let Some(cur) = &current else { continue };
            let mut parts = rec.trim().split(',');
            if let (Some(l), Some(c)) = (parts.next(), parts.next()) {
                if let (Ok(l), Ok(c)) = (l.parse::<u32>(), c.parse::<u64>()) {
                    *out.entry(cur.clone()).or_default().entry(l).or_default() += c;
                }
            }
        } else if line == "end_of_record" {
            current = None;
        }
    }
    out
}

/// Intersect a diff's changed lines with lcov hit counts. lcov paths may be
/// absolute or repo-relative; matching is by suffix, the same tolerance the
/// diff attribution already uses.
pub fn coverage_delta(
    changed: &BTreeMap<String, BTreeSet<u32>>,
    lcov: &BTreeMap<String, BTreeMap<u32, u64>>,
) -> Vec<FileCoverage> {
    let mut out = Vec::new();
    for (path, lines) in changed {
        let Some((_, hits)) = lcov
            .iter()
            .find(|(k, _)| k.as_str() == path || k.ends_with(&format!("/{path}")) || path.ends_with(&format!("/{k}")))
        else {
            // No lcov record for the file at all: unknown, not zero — the
            // file may be untestable (docs, config) or the tool may not
            // instrument it. Saying nothing beats inventing a miss.
            continue;
        };
        let mut covered = 0;
        let mut missed = 0;
        for l in lines {
            match hits.get(l) {
                Some(c) if *c > 0 => covered += 1,
                Some(_) => missed += 1,
                // Not instrumentable (blank/brace lines): not a miss.
                None => {}
            }
        }
        if covered + missed > 0 {
            out.push(FileCoverage {
                path: path.clone(),
                changed_covered: covered,
                changed_missed: missed,
            });
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use mogeung_core::change::{FileChange, Hunk};

    fn hunk(header: &str, lines: &[&str]) -> Hunk {
        Hunk {
            anchor: "a".into(),
            header: header.into(),
            lines: lines.iter().map(|s| s.to_string()).collect(),
            insertions: 0,
            deletions: 0,
            flags: vec![],
            score: 0,
            reviewed: false,
        }
    }

    fn file(path: &str, hunks: Vec<Hunk>) -> FileChange {
        FileChange {
            path: path.into(),
            old_path: None,
            status: mogeung_core::change::FileStatus::Modified,
            insertions: 0,
            deletions: 0,
            hunks,
            flags: vec![],
            score: 0,
            truncated: false,
        }
    }

    #[test]
    fn changed_lines_follow_the_new_side_of_the_hunk() {
        let f = file(
            "src/a.rs",
            vec![hunk("@@ -10,3 +20,4 @@", &[" ctx", "+new1", "-old", "+new2", " ctx"])],
        );
        let map = changed_new_lines(&[f]);
        let lines: Vec<u32> = map["src/a.rs"].iter().copied().collect();
        // 20 ctx, 21 +, (old consumes none), 22 +, 23 ctx
        assert_eq!(lines, vec![21, 22]);
    }

    #[test]
    fn lcov_parses_and_intersects_only_changed_lines() {
        let lcov = parse_lcov("SF:/repo/src/a.rs\nDA:21,1\nDA:22,0\nDA:99,5\nend_of_record\n");
        let mut changed = BTreeMap::new();
        changed.insert("src/a.rs".to_string(), BTreeSet::from([21u32, 22, 40]));
        let delta = coverage_delta(&changed, &lcov);
        assert_eq!(delta.len(), 1);
        assert_eq!(delta[0].changed_covered, 1, "line 21 hit");
        assert_eq!(delta[0].changed_missed, 1, "line 22 instrumented and unhit");
        // line 40 has no DA record: unknown, counted neither way.
    }

    #[test]
    fn a_file_without_lcov_records_reports_nothing_rather_than_zero() {
        let lcov = parse_lcov("SF:src/other.rs\nDA:1,1\nend_of_record\n");
        let mut changed = BTreeMap::new();
        changed.insert("docs/readme.md".to_string(), BTreeSet::from([1u32]));
        assert!(coverage_delta(&changed, &lcov).is_empty());
    }

    #[tokio::test]
    async fn a_run_captures_exit_and_tail() {
        let r = run("/tmp", "echo hello && exit 3", &[]).await;
        assert_eq!(r.exit, Some(3));
        assert!(r.tail.contains("hello"));
    }

    #[tokio::test]
    async fn an_unstartable_command_degrades() {
        let r = run("/nonexistent-dir-xyz", "true", &[]).await;
        assert!(r.exit.is_none());
        assert!(r.tail.contains("could not start"));
    }
}
