#!/usr/bin/env bash
# Regenerate STATUS.md from evidence: git, tests, feature frontmatter, ADRs.
#
# Nothing here is hand-written, which is the point. A PROGRESS.md maintained by
# hand goes stale because it is prose frozen at a moment; a status derived from
# the repository cannot lie and never needs garbage collecting.
#
# This is roadmap item R-H4 (derived progress) built for ourselves first.

set -uo pipefail
cd "$(dirname "$0")/.."

out=STATUS.md

# --- evidence -----------------------------------------------------------------
#
# Deliberately NOT recorded: the commit hash, the uncommitted-file count, a
# generation timestamp, or a git log excerpt.
#
# Each of those makes the file invalidate itself. A status naming its own commit
# is stale the instant it is committed; a timestamp changes on every run; a log
# excerpt shifts by one entry each time. The result is endless churn carrying no
# information, and `git log` already answers those questions better.
#
# The rule: STATUS.md must be a pure function of project state, so regenerating
# it when nothing has changed produces no diff at all. That is what makes a
# derived file trustworthy rather than noise.
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "—")
rust_lines=$(find crates -name '*.rs' -exec cat {} + 2>/dev/null | wc -l | tr -d ' ')
doc_count=$(find docs -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
adr_count=$(ls docs/decisions/*.md 2>/dev/null | wc -l | tr -d ' ')

# Tests: only counted if they actually pass right now.
if test_out=$(cargo test --workspace 2>&1); then
    tests=$(printf '%s' "$test_out" | grep -E '^test result' \
        | awk '{p+=$4} END {print p+0}')
    test_state="passing"
else
    tests=$(printf '%s' "$test_out" | grep -E '^test result' \
        | awk '{p+=$4} END {print p+0}')
    test_state="**FAILING**"
fi

# Assumption ledger tallies.
#
# Count only ledger rows — lines beginning "| A<digit>" — so the status-legend
# table further up the same file is not mistaken for data.
ledger=docs/product/assumptions.md
count_status() {
    grep -E '^\| A[0-9]+ \|' "$ledger" 2>/dev/null | grep -c "\`$1\`" || echo 0
}
a_untested=$(count_status UNTESTED)
a_risk=$(count_status "AT RISK")
a_supported=$(count_status SUPPORTED)
a_refuted=$(count_status REFUTED)

# --- write --------------------------------------------------------------------
{
    echo "# Status"
    echo
    echo "**Generated by \`scripts/gen-status.sh\`. Do not edit — run the script.**"
    echo
    echo "| | |"
    echo "|---|---|"
    echo "| Branch | \`$branch\` |"
    echo "| Tests | $tests $test_state |"
    echo "| Rust | $rust_lines lines |"
    echo "| Docs | $doc_count files, $adr_count ADRs |"
    echo
    echo "## Assumptions"
    echo
    echo "Untested: **$a_untested** · At risk: **$a_risk** · Supported: $a_supported · Refuted: $a_refuted"
    echo
    if [ "$a_untested" -gt 0 ]; then
        echo "> Untested assumptions outnumber evidence. See"
        echo "> [docs/product/assumptions.md](docs/product/assumptions.md) before"
        echo "> starting new work."
        echo
    fi

    echo "## Features in flight"
    echo
    found=0
    for f in docs/features/*.md; do
        [ -e "$f" ] || continue
        [ "$(basename "$f")" = "README.md" ] && continue
        title=$(grep -m1 '^title:' "$f" | sed 's/title:[[:space:]]*//')
        state=$(grep -m1 '^status:' "$f" | sed 's/status:[[:space:]]*//')
        dep=$(grep -m1 '^depends_on:' "$f" | sed 's/depends_on:[[:space:]]*//')
        [ "$found" -eq 0 ] && { echo "| Feature | Status | Depends on |"; echo "|---|---|---|"; }
        echo "| [$title]($f) | \`$state\` | ${dep:-—} |"
        found=1
    done
    [ "$found" -eq 0 ] && echo "None. Priority is unresolved — see [roadmap item 0](docs/product/roadmap.md)."
    echo

} > "$out"

printf 'wrote %s (%s tests %s, %s untested assumptions)\n' \
    "$out" "$tests" "$test_state" "$a_untested"
